#This abstracts the generated source files in the design. DO NOT EDIT. This document is generated by PSoC Creator design builds.

GEN_SOURCE_DIR= Generated_Source/PSoC5

GEN_C_SOURCE_CortexM3=\
	$(GEN_SOURCE_DIR)/MotorController_MotorController.c\
	$(GEN_SOURCE_DIR)/MotorController_DirectionReg.c\
	$(GEN_SOURCE_DIR)/MotorController_DirectionReg_PM.c\
	$(GEN_SOURCE_DIR)/MotorController_Pwm.c\
	$(GEN_SOURCE_DIR)/MotorController_Pwm_PM.c\
	$(GEN_SOURCE_DIR)/CyDmac.c\
	$(GEN_SOURCE_DIR)/CyFlash.c\
	$(GEN_SOURCE_DIR)/CyLib.c\
	$(GEN_SOURCE_DIR)/cyPm.c\
	$(GEN_SOURCE_DIR)/CySpc.c\
	$(GEN_SOURCE_DIR)/cyutils.c\
	$(GEN_SOURCE_DIR)/cy_em_eeprom.c\
	$(GEN_SOURCE_DIR)/Out_Left_Speed.c\
	$(GEN_SOURCE_DIR)/Out_Left_Direction.c\
	$(GEN_SOURCE_DIR)/Out_Right_Speed.c\
	$(GEN_SOURCE_DIR)/Out_Right_Direction.c\
	$(GEN_SOURCE_DIR)/Out_LED.c\
	$(GEN_SOURCE_DIR)/UART.c\
	$(GEN_SOURCE_DIR)/UART_PM.c\
	$(GEN_SOURCE_DIR)/UART_INT.c\
	$(GEN_SOURCE_DIR)/UART_BOOT.c\
	$(GEN_SOURCE_DIR)/InterruptCommandReceived.c\
	$(GEN_SOURCE_DIR)/UART_IntClock.c

GEN_ASM_SOURCE_CortexM3=\
	$(GEN_SOURCE_DIR)/CyBootAsmGnu.s

GEN_SEP_C_SOURCE_CortexM3=\
	$(GEN_SOURCE_DIR)/cyfitter_cfg.c\
	$(GEN_SOURCE_DIR)/cymetadata.c\
	$(GEN_SOURCE_DIR)/Cm3Start.c

GEN_LIBS_CortexM3=\
	Export/ARM_GCC_Generic/CyComponentLibrary.a

